### PR TITLE
fix: serialization empty response without id

### LINKED ISSUE #588: Client fails to deserialize JSON-RPC response without `id` field
- **Target:** client
- **Component:** sdk-client
- **Scenarios:** `initialize`

### Root cause

The conformance runner server sends a JSON-RPC response that contains a `result` field but no `id`
field. The `JSONRPCMessagePolymorphicSerializer` classifies it as a `JSONRPCResponse`, but `JSONRPCResponse.id` is
non-nullable and has no default, so kotlinx.serialization throws `MissingFieldException`. The
`StreamableHttpClientTransport` does not handle this case.

### PR DESCRIPTION
**Pull request by devcrocod**
fixes #588 

## How Has This Been Tested?
conformance test

## Breaking Changes
NaN

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist
- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have added or updated documentation as needed

### CODE REVIEW

File: kotlin-sdk-core/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types/serializers.kt [hunk 1]
```diff
@@ -371,21 +371,23 @@ internal object ServerResultPolymorphicSerializer :
...
+ * - "result" + "id" -> JSONRPCResponse
+ * - "result" -> JSONRPCEmptyMessage
  * - "method" + "id" -> JSONRPCRequest
  * - "method" -> JSONRPCNotification
  */
 internal object JSONRPCMessagePolymorphicSerializer :
     JsonContentPolymorphicSerializer<JSONRPCMessage>(JSONRPCMessage::class) {
     override fun selectDeserializer(element: JsonElement): DeserializationStrategy<JSONRPCMessage> {
-        val jsonObject = element.jsonObject
+        val jsonObj = element.jsonObject
```
Comment (e5l) [inline kotlin-sdk-core/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types/serializers.kt:382]: We should check if we can fix it with schema changes. Could you log an issue to review for this case?

Comment (devcrocod) [reply kotlin-sdk-core/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/types/serializers.kt:382]: Yes, sure
we already have an issue for the json rpc response #545  
I added a comment about this case
