### PR TITLE
Fix providing progressToken with request

### LINKED ISSUE #220: Impossible to add progressToken and use onProgress callback
**Describe the bug**
When trying to add progress notifications to a request, setting the `RequestOptions.onProgress` lambda in the `callTool` method does not include `progressToken` in the `_meta` of the request.

**To Reproduce**
1. Add tool to server that can support progress notifications by trying to extract the progress token from `_meta`.
```kotlin
RegisteredTool(
  Tool(
    name = "progressFail",
    description = "Fails with null pointer exception",
    inputSchema = Tool.Input(),
    outputSchema = Tool.Output(),
    annotations = null,
  ),
) { request ->
  val progressToken = request._meta["progressToken"]?.let { jsonElement ->
    Json.decodeFromJsonElement<ProgressToken>(jsonElement)
  }
  progressToken!! // throws NPE
}
```
2. Connect a client to the server an make a call tool request like so:
```kotlin
client.callTool(
  CallToolRequest(
    name = "progressFail",
  ),
  RequestOptions(
    onProgress = {
      progress.progress / progress.total
    }
  )
)
```
3. Server will throw NPE
4. Try to set progressToken manually on request:
```kotlin
client.callTool(
  CallToolRequest(
    name = "progressFail",
    _meta = buildJsonObject {
      put("progressToken", 1234) // we don't have access to the request id here so it's impossible to associate the onProgress callback with this token
    },
  ),
  RequestOptions(
    onProgress = {
      progress.progress / progress.total // will never be called because it is associated to request id
    }
  )
)
```
5. Receive log messages about a progress notification for an unknown token.

**Expected behavior**
I expect to be able to both register an `onProgress` callback on a `callTool` invocation, and be able to extract that token on the server to send it back with the notification.

**Logs**
Log of NPE when not manually setting token:
```json
{"timestamp":"2025-08-07T21:30:58.052","level":"INFO","logger.thread_name":"docker-java-stream-1030446516","logger.name":"...","message":"{\"timestamp\":\"2025-08-08T01:30:58.043\",\"level\":\"ERROR\",\"logger.thread_name\":\"DefaultDispatcher-worker-2\",\"logger.name\":\"io.modelcontextprotocol.kotlin.sdk.shared.Protocol\",\"message\":\"Error handling request: tools/call (id: NumberId(value=4))\",\"error.stack\":\"java.lang.NullPointerException: null\\n\\tat 
...
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\\n\\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)\\n\\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)\\n\",\"error.kind\":\"java.lang.NullPointerException\"}"}
```

Logs when attempting to set token manually in `_meta` on a request:
```json
{"timestamp":"2025-08-07T20:58:26.981","level":"ERROR","logger.thread_name":"DefaultDispatcher-worker-5 @SseMcpClientTransport.connect#385137368#23","logger.name":"io.modelcontextprotocol.kotlin.sdk.shared.Protocol","message":"Received a progress notification for an unknown token: {\"progress\":0,\"progressToken\":12345,\"_meta\":{},\"total\":5.0,\"method\":\"notifications/progress\"}"}
{"timestamp":"2025-08-07T20:58:27.983","level":"ERROR","logger.thread_name":"DefaultDispatcher-worker-5 @SseMcpClientTransport.connect#385137368#23","logger.name":"io.modelcontextprotocol.kotlin.sdk.shared.Protocol","message":"Received a progress notification for an unknown token: {\"progress\":1,\"progressToken\":12345,\"_meta\":{},\"total\":5.0,\"method\":\"notifications/progress\"}"}
```

**Additional context**

### PR DESCRIPTION
**Pull request by devcrocod**
## Motivation and Context
fix #220 

## How Has This Been Tested?
locally

## Breaking Changes
None

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist
- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have added or updated documentation as needed

### CODE REVIEW

File: kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+    }
+}
+
+private class TestProtocol : Protocol(null) {
+    override fun assertCapabilityForMethod(method: Method) {}
+    override fun assertNotificationCapability(method: Method) {}
+    override fun assertRequestHandlerCapability(method: Method) {}
+}
+
+private class RecordingTransport : Transport {
```
Comment (kpavlov) [inline kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt:162]: good stuff, let's extract it

File: kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+    private val sentMessages = Channel<JSONRPCMessage>(Channel.UNLIMITED)
+    private var onMessageCallback: (suspend (JSONRPCMessage) -> Unit)? = null
+    private var onCloseCallback: (() -> Unit)? = null
+
+    override suspend fun start() {}
```
Comment (kpavlov) [inline kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt:167]: it make sense to add debug logging here

File: kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+
+        assertEquals(setOf("_meta"), params.keys)
+        assertEquals(McpJson.encodeToJsonElement(sent.id), meta["progressToken"])
+
+        transport.deliver(JSONRPCResponse(sent.id, EmptyResult()))
+        inFlight.await()
+    }
+}
+
+private class TestProtocol : Protocol(null) {
```
Comment (kpavlov) [inline kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt:156]: good stuff, let's extract it

File: kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt [hunk 4]
```diff
@@ -0,0 +1,199 @@
...
+        }
+
+        val sent = transport.awaitRequest()
+        val params = requireNotNull(sent.params).jsonObject
+        val meta = params["_meta"]!!.jsonObject
+
+        assertEquals("test://resource", params["uri"]!!.jsonPrimitive.content)
+        assertEquals("customValue", meta["customField"]!!.jsonPrimitive.content)
+        assertEquals(123, meta["anotherField"]!!.jsonPrimitive.int)
+        assertEquals(McpJson.encodeToJsonElement(sent.id), meta["progressToken"])
```
Comment (kpavlov) [inline kotlin-sdk-core/src/commonTest/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/ProtocolTest.kt]: with kotest it might be a bit more readable:

```suggestion
        val sent = transport.awaitRequest()

        val params = sent.params?.jsonObject.shouldNotBeNull()
        params["uri"] shouldBe JsonPrimitive("test://resource")

        val meta = params["_meta"]?.jsonObject.shouldNotBeNull()
        meta["customField"] shouldBe JsonPrimitive("customValue")
        meta["anotherField"] shouldBe JsonPrimitive(123)
        meta["progressToken"] shouldBe McpJson.encodeToJsonElement(sent.id)
```
