### PR TITLE
Test and fix #52

### LINKED ISSUE #52: Incorrect URL in `mcpSse` Client
**Summary:**  
Client requests `.../sse//message?sessionId=...` instead of `.../message?sessionId=...`, causing 404 errors.

### Steps to Reproduce

```kotlin
// Server (works)
embeddedServer(CIO, host = "0.0.0.0", port = port) {
    MCP { configureServer() }
}.start(wait = true)

// Client (broken)
val client = HttpClient(CIO) {
    install(SSE)
}.mcpSse("http://localhost:$port/sse")
```

### Issue  
Trailing slash in the base URL causes double slashes in the request path.

### Impact  
Breaks client-server communication unless manually corrected.

### PR DESCRIPTION
**Pull request by AbdullatifGhajar**
include a test to reproduce the issue #52 and solve it

## Motivation and Context
SSE client can't connect to an SSE server because of wrong url handling

## How Has This Been Tested?
An integration test has been written, in which an SSE client should successfully connect to an SSE server without mocking

## Breaking Changes
No breaking changes

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have added or updated documentation as needed

### CODE REVIEW

File: src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt [hunk 1]
```diff
@@ -39,7 +39,7 @@ public class SseClientTransport(
     private var job: Job? = null
 
     private val baseUrl by lazy {
-        session.call.request.url.toString().removeSuffix("/")
+        session.call.request.url.toString().removeSuffix("/sse")
```
Comment (e5l) [inline src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/client/SSEClientTransport.kt:42]: I would prefer to keep the prefix to have an explicit URL, but use the correct URL concatenation method to avoid duplicate // in path segments. There are several methods for `pathSegment` in Ktor you can use or build your own.

**Review by e5l — CHANGES_REQUESTED** [review]
please check the comment

**Review by e5l — APPROVED** [review]
lgtm as discussed
